export const LOGIN = 'LOGIN';

export const FETCH_TRIPS_START = 'FETCH_TRIPS_START';
export const FETCH_TRIPS_SUCCESS = 'FETCH_TRIPS_SUCCESS';
export const FETCH_TRIPS_FAIL = 'FETCH_TRIPS_FAIL';

export const FETCH_TRIP_START = 'FETCH_TRIP_START';
export const FETCH_TRIP_SUCCESS = 'FETCH_TRIP_SUCCESS';
export const FETCH_TRIP_FAIL = 'FETCH_TRIP_FAIL';

export const CREATE_TRIPS_START = 'CREATE_TRIPS_START';
export const CREATE_TRIPS_SUCCESS = 'CREATE_TRIPS_SUCCESS';
export const CREATE_TRIPS_FAIL = 'CREATE_TRIPS_FAIL';

export const DELETE_TRIP_START = 'FETCH_TRIP_START';
export const DELETE_TRIP_SUCCESS = 'FETCH_TRIP_SUCCESS';
export const DELETE_TRIP_FAIL = 'FETCH_TRIP_FAIL';

export const FETCH_DESTINATION = 'FETCH_DESTINATION';
export const LOCATIONS_START = 'LOCATIONS_START';
export const LOCATIONS_SUCCESS = 'LOCATIONS_SUCCESS';
export const LOCATIONS_FAIL = 'LOCATIONS_FAIL';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOAD_USER = 'LOAD_USER';
export const AUTH_ERROR = 'AUTH_ERROR';
export const USER_ROLE_CHANGED = 'USER_ROLE_CHANGED';
export const ERROR = 'ERROR';
export const SUCCESS = 'SUCCESS';
export const GET_LIST = 'GET_LIST';

export const FIND_USER = 'FIND_USER';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const REGISTER_START = 'REGISTER_START';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const VIEW_PROFILE_PENDING = 'VIEW_PROFILE_PENDING';
export const VIEW_PROFILE_SUCCESS = 'VIEW_PROFILE_SUCCESS';
export const VIEW_PROFILE_ERROR = 'VIEW_PROFILE_ERROR';

export const UPDATE_PROFILE_PENDING = 'UPDATE_PROFILE_PENDING';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_ERROR = 'UPDATE_PROFILE_ERROR';
export const GET_TRIPS_AUTOSEARCH = 'GET_TRIPS_AUTOSEARCH';

export const SAVE_TOKEN = 'SAVE_TOKEN';
export const LOAD = 'LOAD_USER';

export const GET_TRIPS = 'GET_TRIPS';
